#!/bin/sh

day=day$1
command=$2

[ -z "$command" ] && command=run

case "$command" in
    stub) if [ ! -d "$day" ]; then
              mkdir $day
              for x in one two; do
              ( cat <<EOF
let () =
  let data = In_channel.read_lines "test" in
EOF
              ) >> $day/${x}.ml
              done
              touch $day/test $day/instructions.troff $day/input
          fi
          ;;
    *)
        pushd $day >/dev/null
        BIN=$day mk -f ../mkfile $command
        popd >/dev/null
        ;;
esac
